# EXIBE A VERSÃO DO BANCO DE DADOS
SELECT VERSION();

# EXIBE TODAS AS INSTÂNCIAS DE BANCO DISPONIVEIS
SHOW DATABASES;

# CRIAR UMA INSTÂNCIA DE BANCO DE DADOS
CREATE DATABASE BANCO;

# APAGAR O BANCO DE DADOS
DROP DATABASE BANCO;

# CONECTA A UMA INSTANCIA DO BANCO DE DADOS
USE BANCO;

# MOSTRA TODAS AS TABELAS DO BANCO
SHOW TABLES;

#----------------------------------------------------------------------------------------------------------------

# CRIANDO TABELAS

# CRIANDO A TABELA CLIENTE
CREATE TABLE cliente(
	cli_cpf INT PRIMARY KEY, # NOT NULL É PADRÃO DA PK
	cli_nome VARCHAR(255) NOT NULL,
	cli_rua VARCHAR(255) NOT NULL,
	cli_numero INT NOT NULL,
	cli_bairro VARCHAR(255) NOT NULL,
	cli_telefone VARCHAR(11) NOT NULL
);

# CRIANDO A TABELA PEDIDO
CREATE TABLE pedido(
	ped_numero INT PRIMARY KEY,
	ped_data DATE
);

# CRIANDO A TABELA PRODUTO
CREATE TABLE produto(
	prod_codigo INT PRIMARY KEY,
	prod_nome VARCHAR(255),
	prod_preco FLOAT
);

# MOSTRA AS CARACTERISTICAS DOS ATRIBUITOS DA TABELA;
DESCRIBE cliente;

# SELECIONA TODAS AS COLUNAS DA TABELA
SELECT * FROM cliente;

# APAGA UMA TABELA
DROP TABLE cliente;